# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsTest
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'XCoordinator/RxSwift'
  pod 'Kingfisher'
  pod 'SVProgressHUD'
  pod 'SwifterSwift'

end
